services:
 redis:
  image: redis:7.4
  restart: unless-stopped
  ports:
   - "6379:6379"

 postgres:
  image: postgres:16.4
  restart: unless-stopped
  environment:
   POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
  ports:
   - "5432:5432"
  volumes:
   - db-data:/var/lib/postgresql/data

 nirn:
  image: ghcr.io/germanoeich/nirn-proxy:v1.3.3
  restart: unless-stopped
  environment:
   REQUEST_TIMEOUT: 15000

 ayako-dev:
  build:
   context: .
   dockerfile: ./packages/Bot/Dockerfile
  working_dir: /app/packages/Bot
  command: ["pnpm", "dev"]
  restart: unless-stopped
  depends_on:
   - postgres
   - redis
   - nirn

 ayako:
  build:
   context: .
   dockerfile: ./packages/Bot/Dockerfile
  working_dir: /app/packages/Bot
  command: ["pnpm", "start"]
  restart: unless-stopped
  depends_on:
   - postgres
   - redis
   - nirn

 api:
  build:
   context: .
   dockerfile: ./packages/Server/Dockerfile
  working_dir: /app/packages/Server
  restart: unless-stopped
  command: ["pnpm", "start"]
  depends_on:
   - postgres
   - redis

 psqlExporter:
  image: quay.io/prometheuscommunity/postgres-exporter
  restart: unless-stopped
  environment:
   DATA_SOURCE_URI: "postgres:5432/postgres?sslmode=disable"
   DATA_SOURCE_USER: ${DATABASE_USER_READONLY}
   DATA_SOURCE_PASS: ${DATABASE_PASSWORD}
  depends_on:
   - postgres

 cloudflared:
  image: cloudflare/cloudflared:latest
  command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TOKEN}
  restart: unless-stopped

 # kiyu:
 #   build:
 #    context: ../Kiyu
 #    dockerfile: ../Kiyu/Dockerfile
 #   restart: unless-stopped
 #   depends_on:
 #     - postgres

 # Kitten-PayPal:
 #   image: node:22
 #   restart: unless-stopped
 #   depends_on:
 #     - postgres
 #   command: sh -c "npm i -g pnpm && pnpm i && pnpx prisma db push && pnpm start"

 # Reiko:
 #   image: node:22
 #   restart: unless-stopped
 #   depends_on:
 #     - postgres
 #   command: sh -c "npm i -g pnpm && pnpm i && pnpx prisma db push && pnpm start"

 grafana:
  image: grafana/grafana:latest
  restart: unless-stopped
  volumes:
   - grafana-data:/var/lib/grafana
   - ./metrics/dashboards:/etc/grafana/provisioning/dashboards
   - ./metrics/datasources:/etc/grafana/provisioning/datasources

 prometheus:
  image: prom/prometheus
  restart: unless-stopped
  volumes:
   - prometheus-data:/prometheus
   - ./metrics/prometheus.yml:/etc/prometheus/prometheus.yml

volumes:
 db-data:
 grafana-data:
 prometheus-data:
