{
 "title": "Ayako API",
 "time": { "from": "2024-11-06T10:19:07.144Z", "to": "2024-11-06T10:34:07.144Z" },
 "templating": {
  "list": [
   {
    "name": "status",
    "query": {
     "query": "label_values(ayako_api_responses,status)"
    }
   },
   {
    "name": "apiVersion",
    "query": {
     "query": "label_values(ayako_api_calls,apiVersion)"
    }
   },
   {
    "name": "path",
    "query": {
     "query": "label_values(ayako_api_calls,path)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(ayako_api_calls,method)"
    }
   },
   {
    "name": "resPath",
    "query": {
     "query": "label_values(ayako_api_responses,path)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests by Path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (path) (rate(ayako_api_calls{path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests by Method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(ayako_api_calls{method=~\"$method\"}[$__rate_interval]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (apiVersion, method, path) (rate(ayako_api_calls{apiVersion=~\"$apiVersion\",method=~\"$method\",path=~\"$path\"}[$__rate_interval]))",
     "legendFormat": "{{apiVersion}} {{method}} {{path}}"
    }
   ]
  },
  {
   "title": "Response Codes",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "reqpm" } },
   "targets": [
    {
     "expr": "sum by (status, path) (rate(ayako_api_responses{status=~\"$status\",path=~\"$resPath\"}[$__rate_interval]))",
     "legendFormat": "{{status}} {{path}}"
    }
   ]
  }
 ]
}