{
 "title": "Ayako Gateway",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "clientName", "query": { "query": "label_values(clientName)" } },
   { "name": "shardId", "query": { "query": "label_values(shard)" } }
  ]
 },
 "panels": [
  {
   "title": "Gateway Events",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(eventType) (rate(ayako_gateway_dispatch_events{clientName=~\"$clientName\",shard=~\"$shardId\"}[$__rate_interval]))",
     "legendFormat": "{{eventType}}"
    }
   ]
  },
  {
   "title": "Total Gateway Events",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "eps" } },
   "targets": [
    {
     "expr": "sum by(clientName) (rate(ayako_gateway_dispatch_events{clientName=~\"$clientName\", shard=~\"$shardId\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum (rate(ayako_gateway_dispatch_events{clientName=~\"$clientName\", shard=~\"$shardId\"}[$__rate_interval]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Shard Events Received",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "epm" } },
   "targets": [
    {
     "expr": "sum by(opCode) (rate(ayako_gateway_shard_receive_events{clientName=~\"$clientName\", shard=~\"$shardId\"}[$__rate_interval])) * 60",
     "legendFormat": "{{opCode}}"
    }
   ]
  },
  {
   "title": "Shard Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "ayako_gateway_shard_latency{clientName=~\"$clientName\", shard=~\"$shardId\"}",
     "legendFormat": "Shard {{shard}}"
    }
   ]
  }
 ]
}