{
 "title": "Nirn Proxy",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "clientId",
    "query": {
     "query": "label_values(nirn_proxy_requests_count, clientId)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Invalid Reqs Total (1h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nirn_proxy_requests_count{status=~\"401 Unauthorized|403 Forbidden|429 Too Many Requests\",clientId=~\"$clientId\"}[1h]))"
    }
   ]
  },
  {
   "title": "Invalid Reqs (1h)",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(nirn_proxy_requests_count{status=\"401 Unauthorized\",clientId=~\"$clientId\"}[1h]))",
     "legendFormat": "401"
    },
    {
     "expr": "sum(increase(nirn_proxy_requests_count{status=\"403 Forbidden\",clientId=~\"$clientId\"}[1h]))",
     "legendFormat": "403"
    },
    {
     "expr": "sum(increase(nirn_proxy_requests_count{status=\"429 Too Many Requests\",clientId=~\"$clientId\"}[1h]))",
     "legendFormat": "429"
    }
   ]
  },
  {
   "title": "Reqs /s (curr)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Reqs/s",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[$__rate_interval])) by (clientId)",
     "legendFormat": "{{clientId}}"
    },
    {
     "expr": "sum(rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[1m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "401",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, status, route) (rate(nirn_proxy_requests_count{status=\"401 Unauthorized\",clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "403",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, status, route) (rate(nirn_proxy_requests_count{status=\"403 Forbidden\",clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}} "
    }
   ]
  },
  {
   "title": "429",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, status, route) (rate(nirn_proxy_requests_count{status=\"429 Too Many Requests\",clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "5XX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(method, status, route) (rate(nirn_proxy_requests_count{status=~\"500 Internal Server Error|501 Not Implemented|502 Bad Gateway|503 Service Unavailable|504 Gateway Timeout|505 HTTP Version Not Supported|506 Variant Also Negotiates|507 Insufficient Storage|508 Loop Detected|510 Not Extended|511 Network Authentication Required\", clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}} ({{status}})"
    }
   ]
  },
  {
   "title": "Status codes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (status) (rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method, route) (rate(nirn_proxy_requests_count{clientId=~\"$clientId\"}[$__rate_interval]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(nirn_proxy_requests_bucket{clientId=~\"$clientId\"}[5m])) by (le))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(nirn_proxy_requests_bucket{clientId=~\"$clientId\"}[5m])) by (le))",
     "legendFormat": "95th"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nirn_proxy_requests_bucket{clientId=~\"$clientId\"}[5m])) by (le))",
     "legendFormat": "99th"
    }
   ]
  },
  {
   "title": "Latency 90th",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(nirn_proxy_requests_bucket{clientId=~\"$clientId\"}[5m])) by (le, method, route))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latency 99th",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(nirn_proxy_requests_bucket{clientId=~\"$clientId\"}[5m])) by (le, method, route))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Open connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "sum(nirn_proxy_open_connections)",
     "legendFormat": "Connections Open"
    }
   ]
  }
 ]
}