{
 "title": "Ayako Database",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "action", "query": { "query": "label_values(action)" } },
   { "name": "modelName", "query": { "query": "label_values(modelName)" } }
  ]
 },
 "panels": [
  {
   "title": "Latency by action",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(action) (ayako_db_query_latency{modelName=~\"$modelName\",action=~\"$action\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Latency by model",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum by(modelName) (ayako_db_query_latency{modelName=~\"$modelName\",action=~\"$action\"})",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "DB Query Execute",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum by(action, modelName) (rate(ayako_db_query_execute{modelName=~\"$modelName\",action=~\"$action\"}[$__rate_interval]))",
     "legendFormat": "{{action}} {{modelName}}"
    }
   ]
  },
  {
   "title": "Usage by action",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "sum by(action) (rate(ayako_db_query_execute{modelName=~\"$modelName\",action=~\"$action\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Usage by model",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "sum by(modelName) (rate(ayako_db_query_execute{modelName=~\"$modelName\",action=~\"$action\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}