{
 "title": "Ayako Stats",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Command", "query": { "query": "label_values(command)" } },
   { "name": "Type", "query": { "query": "label_values(type)" } },
   { "name": "Context", "query": { "query": "label_values(context)" } }
  ]
 },
 "panels": [
  { "title": "Commands", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Commands by Type",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by(type) (rate(ayako_command_executed{command=~\"$Command\", type=~\"$Type\", context=~\"$Context\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands by Context",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum by(context) (rate(ayako_command_executed{command=~\"$Command\", type=~\"$Type\", context=~\"$Context\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Commands",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by(command) (rate(ayako_command_executed{command=~\"$Command\", type=~\"$Type\", context=~\"$Context\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Guilds",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_guild_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Users",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_user_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Emojis",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_emoji_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Roles",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_role_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Channels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_channel_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Stickers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_sticker_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Clusters",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_cluster_count", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Shards",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ayako_shard_count", "legendFormat": "__auto" }
   ]
  }
 ]
}