global:
  scrape_interval: 5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'codelab-monitor'

alerting:
  alertmanagers:
    - static_configs:
        - targets:

rule_files:

scrape_configs:
  - job_name: 'nirn-dev'
    static_configs:
      - targets: ['nirn-dev:9000']
